/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppPodsIndexRouteImport } from './routes/_app.pods.index'
import { Route as AppPodsDeployRouteImport } from './routes/_app.pods.deploy'
import { Route as AppApiUsageRouteImport } from './routes/_app.api.usage'
import { Route as AppApiKeysRouteImport } from './routes/_app.api.keys'
import { Route as AppApiCatalogRouteImport } from './routes/_app.api.catalog'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPodsIndexRoute = AppPodsIndexRouteImport.update({
  id: '/pods/',
  path: '/pods/',
  getParentRoute: () => AppRoute,
} as any)
const AppPodsDeployRoute = AppPodsDeployRouteImport.update({
  id: '/pods/deploy',
  path: '/pods/deploy',
  getParentRoute: () => AppRoute,
} as any)
const AppApiUsageRoute = AppApiUsageRouteImport.update({
  id: '/api/usage',
  path: '/api/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api/keys',
  path: '/api/keys',
  getParentRoute: () => AppRoute,
} as any)
const AppApiCatalogRoute = AppApiCatalogRouteImport.update({
  id: '/api/catalog',
  path: '/api/catalog',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/api/catalog': typeof AppApiCatalogRoute
  '/api/keys': typeof AppApiKeysRoute
  '/api/usage': typeof AppApiUsageRoute
  '/pods/deploy': typeof AppPodsDeployRoute
  '/pods/': typeof AppPodsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/api/catalog': typeof AppApiCatalogRoute
  '/api/keys': typeof AppApiKeysRoute
  '/api/usage': typeof AppApiUsageRoute
  '/pods/deploy': typeof AppPodsDeployRoute
  '/pods': typeof AppPodsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/api/catalog': typeof AppApiCatalogRoute
  '/_app/api/keys': typeof AppApiKeysRoute
  '/_app/api/usage': typeof AppApiUsageRoute
  '/_app/pods/deploy': typeof AppPodsDeployRoute
  '/_app/pods/': typeof AppPodsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/catalog'
    | '/api/keys'
    | '/api/usage'
    | '/pods/deploy'
    | '/pods/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/api/catalog'
    | '/api/keys'
    | '/api/usage'
    | '/pods/deploy'
    | '/pods'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/api/catalog'
    | '/_app/api/keys'
    | '/_app/api/usage'
    | '/_app/pods/deploy'
    | '/_app/pods/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pods/': {
      id: '/_app/pods/'
      path: '/pods'
      fullPath: '/pods/'
      preLoaderRoute: typeof AppPodsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pods/deploy': {
      id: '/_app/pods/deploy'
      path: '/pods/deploy'
      fullPath: '/pods/deploy'
      preLoaderRoute: typeof AppPodsDeployRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api/usage': {
      id: '/_app/api/usage'
      path: '/api/usage'
      fullPath: '/api/usage'
      preLoaderRoute: typeof AppApiUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api/keys': {
      id: '/_app/api/keys'
      path: '/api/keys'
      fullPath: '/api/keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api/catalog': {
      id: '/_app/api/catalog'
      path: '/api/catalog'
      fullPath: '/api/catalog'
      preLoaderRoute: typeof AppApiCatalogRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppApiCatalogRoute: typeof AppApiCatalogRoute
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppApiUsageRoute: typeof AppApiUsageRoute
  AppPodsDeployRoute: typeof AppPodsDeployRoute
  AppPodsIndexRoute: typeof AppPodsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppApiCatalogRoute: AppApiCatalogRoute,
  AppApiKeysRoute: AppApiKeysRoute,
  AppApiUsageRoute: AppApiUsageRoute,
  AppPodsDeployRoute: AppPodsDeployRoute,
  AppPodsIndexRoute: AppPodsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
