/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppPodsIndexRouteImport } from './routes/_app.pods.index'
import { Route as AppPodsTemplatesRouteImport } from './routes/_app.pods.templates'
import { Route as AppPodsSshKeysRouteImport } from './routes/_app.pods.ssh-keys'
import { Route as AppPodsImagesRouteImport } from './routes/_app.pods.images'
import { Route as AppPodsDeployRouteImport } from './routes/_app.pods.deploy'
import { Route as AppApiUsageRouteImport } from './routes/_app.api.usage'
import { Route as AppApiKeysRouteImport } from './routes/_app.api.keys'
import { Route as AppApiCatalogRouteImport } from './routes/_app.api.catalog'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppPodsIndexRoute = AppPodsIndexRouteImport.update({
  id: '/pods/',
  path: '/pods/',
  getParentRoute: () => AppRoute,
} as any)
const AppPodsTemplatesRoute = AppPodsTemplatesRouteImport.update({
  id: '/pods/templates',
  path: '/pods/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppPodsSshKeysRoute = AppPodsSshKeysRouteImport.update({
  id: '/pods/ssh-keys',
  path: '/pods/ssh-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppPodsImagesRoute = AppPodsImagesRouteImport.update({
  id: '/pods/images',
  path: '/pods/images',
  getParentRoute: () => AppRoute,
} as any)
const AppPodsDeployRoute = AppPodsDeployRouteImport.update({
  id: '/pods/deploy',
  path: '/pods/deploy',
  getParentRoute: () => AppRoute,
} as any)
const AppApiUsageRoute = AppApiUsageRouteImport.update({
  id: '/api/usage',
  path: '/api/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api/keys',
  path: '/api/keys',
  getParentRoute: () => AppRoute,
} as any)
const AppApiCatalogRoute = AppApiCatalogRouteImport.update({
  id: '/api/catalog',
  path: '/api/catalog',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/api/catalog': typeof AppApiCatalogRoute
  '/api/keys': typeof AppApiKeysRoute
  '/api/usage': typeof AppApiUsageRoute
  '/pods/deploy': typeof AppPodsDeployRoute
  '/pods/images': typeof AppPodsImagesRoute
  '/pods/ssh-keys': typeof AppPodsSshKeysRoute
  '/pods/templates': typeof AppPodsTemplatesRoute
  '/pods/': typeof AppPodsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/api/catalog': typeof AppApiCatalogRoute
  '/api/keys': typeof AppApiKeysRoute
  '/api/usage': typeof AppApiUsageRoute
  '/pods/deploy': typeof AppPodsDeployRoute
  '/pods/images': typeof AppPodsImagesRoute
  '/pods/ssh-keys': typeof AppPodsSshKeysRoute
  '/pods/templates': typeof AppPodsTemplatesRoute
  '/pods': typeof AppPodsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/billing': typeof AppBillingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/api/catalog': typeof AppApiCatalogRoute
  '/_app/api/keys': typeof AppApiKeysRoute
  '/_app/api/usage': typeof AppApiUsageRoute
  '/_app/pods/deploy': typeof AppPodsDeployRoute
  '/_app/pods/images': typeof AppPodsImagesRoute
  '/_app/pods/ssh-keys': typeof AppPodsSshKeysRoute
  '/_app/pods/templates': typeof AppPodsTemplatesRoute
  '/_app/pods/': typeof AppPodsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/dashboard'
    | '/settings'
    | '/api/catalog'
    | '/api/keys'
    | '/api/usage'
    | '/pods/deploy'
    | '/pods/images'
    | '/pods/ssh-keys'
    | '/pods/templates'
    | '/pods/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/dashboard'
    | '/settings'
    | '/api/catalog'
    | '/api/keys'
    | '/api/usage'
    | '/pods/deploy'
    | '/pods/images'
    | '/pods/ssh-keys'
    | '/pods/templates'
    | '/pods'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/billing'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_app/api/catalog'
    | '/_app/api/keys'
    | '/_app/api/usage'
    | '/_app/pods/deploy'
    | '/_app/pods/images'
    | '/_app/pods/ssh-keys'
    | '/_app/pods/templates'
    | '/_app/pods/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pods/': {
      id: '/_app/pods/'
      path: '/pods'
      fullPath: '/pods/'
      preLoaderRoute: typeof AppPodsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pods/templates': {
      id: '/_app/pods/templates'
      path: '/pods/templates'
      fullPath: '/pods/templates'
      preLoaderRoute: typeof AppPodsTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pods/ssh-keys': {
      id: '/_app/pods/ssh-keys'
      path: '/pods/ssh-keys'
      fullPath: '/pods/ssh-keys'
      preLoaderRoute: typeof AppPodsSshKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pods/images': {
      id: '/_app/pods/images'
      path: '/pods/images'
      fullPath: '/pods/images'
      preLoaderRoute: typeof AppPodsImagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pods/deploy': {
      id: '/_app/pods/deploy'
      path: '/pods/deploy'
      fullPath: '/pods/deploy'
      preLoaderRoute: typeof AppPodsDeployRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api/usage': {
      id: '/_app/api/usage'
      path: '/api/usage'
      fullPath: '/api/usage'
      preLoaderRoute: typeof AppApiUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api/keys': {
      id: '/_app/api/keys'
      path: '/api/keys'
      fullPath: '/api/keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api/catalog': {
      id: '/_app/api/catalog'
      path: '/api/catalog'
      fullPath: '/api/catalog'
      preLoaderRoute: typeof AppApiCatalogRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppApiCatalogRoute: typeof AppApiCatalogRoute
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppApiUsageRoute: typeof AppApiUsageRoute
  AppPodsDeployRoute: typeof AppPodsDeployRoute
  AppPodsImagesRoute: typeof AppPodsImagesRoute
  AppPodsSshKeysRoute: typeof AppPodsSshKeysRoute
  AppPodsTemplatesRoute: typeof AppPodsTemplatesRoute
  AppPodsIndexRoute: typeof AppPodsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppApiCatalogRoute: AppApiCatalogRoute,
  AppApiKeysRoute: AppApiKeysRoute,
  AppApiUsageRoute: AppApiUsageRoute,
  AppPodsDeployRoute: AppPodsDeployRoute,
  AppPodsImagesRoute: AppPodsImagesRoute,
  AppPodsSshKeysRoute: AppPodsSshKeysRoute,
  AppPodsTemplatesRoute: AppPodsTemplatesRoute,
  AppPodsIndexRoute: AppPodsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
